sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t 883630/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true 883630/docker-react npm run test 